# render.yaml
services:
  - type: web
    name: janitor-proxy-deepseek  # Можно изменить
    env: python
    region: frankfurt  # Самый стабильный регион
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn janitor_proxy:app
    envVars:
      - key: DEEPSEEK_API_KEY
        value: sk-fd06768644384bbfab7f6a74d5f95523  # ⚠️ Замените на реальный ключ!